---
name: Semgrep Full Scan

permissions:
  actions: read
  contents: read
  security-events: write

on:
  workflow_dispatch: {}
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  semgrep-full:
      runs-on: ubuntu-latest
      container:
        image: returntocorp/semgrep
      steps:
        # step 1
        - name: clone application source code
          uses: actions/checkout@v3
        # step 2
        - name: full scan
          run: |
            semgrep \
              --sarif --output report.sarif \
              --metrics=off \
              --config="p/typescript"
        # step 3
        - name: save report as pipeline artifact
          uses: actions/upload-artifact@v3
          with:
            name: report.sarif
            path: report.sarif
        # step 4
        - name: publish code scanning alerts
          uses: github/codeql-action/upload-sarif@v2
          with:
            sarif_file: report.sarif
            category: semgrep