name: Semgrep Scan
on:
  push:
    branches:
      - main
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          semgrep scan \
            --error \
            --metrics=off \
            --config="p/typescript"
